site_name: "Pharos API Documentation"
theme:
  name: material
  features:
    - navigation.sections
  font:
    code: Fira Code
repo_url: https://github.com/Vandy-mHealth/pharos-api

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - stylesheets/_extra.css

nav:
  - Routes: index.md
  - Example Request:
      - User: examples/user.md
      - Landmark: examples/landmark.md
      - Network: examples/network.md
      - Photo: examples/photo.md
  - Schema:
      - General: schemas/index.md
      - User: schemas/user.md
      - Landmark: schemas/landmark.md
      - Network: schemas/network.md
      - Photo: schemas/photo.md
